### Create User
POST http://localhost:7000/
Content-Type: application/json

{
"name": "Thijs Wouters",
"age": 37
}

###

### Create post
POST http://localhost:8000/
Content-Type: application/json

{
  "authorId": "<copy id from user call>",
  "title": "GraphQL works like this",
  "contents": "It just works, after you implement it ofcourse."
}

###

### Create comment
POST http://localhost:9000/
Content-Type: application/json

{
  "authorId": "<copy id from create user call>",
  "postId": "<copy id from create post call>",
  "contents": "No shit, Shirlock"
}

###
